### ISSUE TITLE
(Feature Flaw) Response Messages of Threshold Command

### ISSUE THREAD

**Issue by yu7ong** [AY2425S1-CS2103T-T17-3/tp#121]
**Error message shown may not be specific** 
When I initially entered a command incorrectly, the error message displayed was: “Names should only contain alphanumeric characters and spaces, and it should not be blank.” This message led me to believe that the issue was with the product name rather than my command input. This can create confusion for users who are unsure of the correct command syntax.

As seen from the attached photo: 
<img width="908" alt="image" src="https://github.com/user-attachments/assets/98199c20-4afc-4b4d-aba0-94ec7ac8e596">

**Consider shortening success message** 
Additionally, when setting minimum and maximum thresholds, the messages displayed can be shortened. Shortening these messages would improve readability and overall user experience.
<img width="917" alt="image" src="https://github.com/user-attachments/assets/3d3cc3d2-5118-409b-8f6c-607cba28d676">

**Comment by Anvita2110** [comment]
This is changed in v1.5 hence not in consideration anymore.
