### ISSUE TITLE
[PE-D][Tester C] Unwanted text in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T17-3/tp#169]
### **Description**
There is two section of Quick Start, the above quick start seems to be redundant. There also seems to be extra line of "layout..." that should not be there as it might confuse users.

### **Screenshot**
![Screenshot 2024-11-08 at 4.20.25 PM.png](https://raw.githubusercontent.com/Bonzzz3/ped/main/files/7f971173-e39b-493d-96d4-82ee09cd4ef9.png)

### **Suggested Improvement**
Remove both of the "Quick Start" and "layout..." header.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Bonzzz3/ped#2

**Comment by Anvita2110** [comment]
Closed by #240
