### ISSUE TITLE
[PE-D][Tester D] Outdated UI.png

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T17-3/tp#172]
![Screenshot 2024-11-08 at 4.30.23 PM.png](https://raw.githubusercontent.com/justsparsh/ped/main/files/80592ab8-60dc-473c-8a01-c95ddb5415bd.png)

I tested the add_supplier command. Command was executed successfully as can be seen above. However, the UI did not update to reflect the changes.

Edit: Upon further testing, I realised there is a separate command to view suppliers. However, the UI mockup present in the UG made me believe I should see all information on one screen. I am keeping this as Medium severity because it made it really confusing to use the app

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: justsparsh/ped#4

**Comment by Anvita2110** [comment]
Closed by PR #236
