### ISSUE TITLE
[PE-D][Tester A] UI text box overflows

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T17-3/tp#178]
Error - 
I have entered the command `Fresh Farms Ltd; Phone: 98765432; Email: contact@freshfarms.com; Address: 23 Orchard Streeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeet, Suite 5;`

Actual Output - 
It causes an overflow within the UI text box causing it to truncate.

Expected Output - 
Give an error message informing the user of a maximum limit avoiding an overflow.

![image.png](https://raw.githubusercontent.com/Arnaxx54/ped/main/files/5f352215-4161-49d4-a194-9a0081e46432.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Arnaxx54/ped#4

**Comment by Anvita2110** [comment]
Not considered as a bug based on the course website
<img width="524" alt="384805554-7b6ead8a-c3f1-4a33-a163-08b4b91f438a" src="https://github.com/user-attachments/assets/71aeb0a6-fd19-4467-9913-7393fe31ee04">
