### ISSUE TITLE
[PE-D][Tester A] Information within the developer guide is yet to be updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T17-3/tp#199]
![image.png](https://raw.githubusercontent.com/Arnaxx54/ped/main/files/1c8b0680-731d-4b32-b82c-989fcb74d4c7.png)

It should include the relevant information. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Arnaxx54/ped#10

**Comment by Anvita2110** [comment]
Closed by #242
